### ISSUE TITLE
Display label along with tcin and tcout?

### ISSUE THREAD

**Issue by escorciav** [ina-foss/amalia.js#4]
Hi!

Thanks for releasing this library. I was wondering if it's possible to display all the attributes of the metadata `label`, `tcin`, `tcout`?

I'm using the latest provided package.

Thanks!
Victor

**Comment by nrv** [comment]
Hi,

It depends on which visualization plugin you want to use

Nicolas

Le 07/04/2020 à 07:17, Victor Escorcia Castillo a écrit :

**Comment by escorciav** [comment]
I'm using the [timeline plugin](https://ina-foss.github.io/amalia.js/guide-plugin-timeline-options.html). I want to display a short message on each segment.

Is this possible?
I found that if I added the property `label` into the metadata. It displays my message but it doesn't display the the `tc[inout]`.

**Comment by nrv** [comment]
I think you'll have to patch the code to have this beahaviour :-)

**Comment by escorciav** [comment]
Good to know. Do you happen to remember the relevant stuff that I should take a look at it?
I mean the names of the "attributes" or "classes" that I should read.

BTW, I'm a rookie in JS. I'm on that stage of StackOverflow, copy-paste, works, debug and move on

**Comment by nrv** [comment]
I would say https://github.com/ina-foss/amalia.js/blob/master/src/plugins/timeline/cuepoints-component.js around line 124
Good luck
